# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CalculateXX <- function(X) {
    .Call('_LOCOM_CalculateXX', PACKAGE = 'LOCOM', X)
}

Newton <- function(freq_table, X, XX, beta_init, weight, tol, iter_max, Firth_thresh, robust_var, prop_presence, get_var) {
    .Call('_LOCOM_Newton', PACKAGE = 'LOCOM', freq_table, X, XX, beta_init, weight, tol, iter_max, Firth_thresh, robust_var, prop_presence, get_var)
}

perm_Newton <- function(freq_table, Yr, X, XX, beta_init, weight, perm, tol, iter_max, Firth_thresh, robust_var, prop_presence, get_var) {
    .Call('_LOCOM_perm_Newton', PACKAGE = 'LOCOM', freq_table, Yr, X, XX, beta_init, weight, perm, tol, iter_max, Firth_thresh, robust_var, prop_presence, get_var)
}

